tunnel: 835bfa24-109b-4850-abcf-08a049f3c278
credentials-file: /root/.cloudflared/835bfa24-109b-4850-abcf-08a049f3c278.json

ingress:
  # SSH access
  - hostname: ssh.ct-42210.com
    service: ssh://localhost:22

  # Cockpit web interface
  - hostname: cockpit.ct-42210.com
    service: http://localhost:9090

  # Pi Kappa Phi photo hosting (nginx)
  - hostname: pikapp-photos.ct-42210.com
    service: http://localhost:8081

  # Nextcloud web interface
  - hostname: ct-42210.com
    service: http://localhost:80

  # Nextcloud with www subdomain
  - hostname: www.ct-42210.com
    service: http://localhost:80

  # Catch-all rule (required)
  - service: http_status:404
